package finalproject;

import java.awt.Image;

import javax.swing.ImageIcon;


public interface ppp {
   ImageIcon pea=new ImageIcon("src/picture/豌豆泡.jpeg");
   ImageIcon backtohome=new ImageIcon("src/picture/返回.png");
   ImageIcon game=new ImageIcon("src/picture/遊戲介紹end.png");
   ImageIcon background=new ImageIcon("src/picture/背景.jpg");
   ImageIcon background3=new ImageIcon("src/picture/太空背景2.jpg");
   ImageIcon background2=new ImageIcon("src/picture/background2改.png");
   ImageIcon dec=new ImageIcon("src/picture/上面木板.jpg");
   ImageIcon ppea=new ImageIcon("src/picture/nobackpea.png");
   ImageIcon pppea=new ImageIcon("src/picture/豌豆按鈕.png");
   ImageIcon bigppea=new ImageIcon("src/picture/nobackpeabig.png");
   ImageIcon pwall=new ImageIcon("src/picture/nobackwall.png");
   ImageIcon ppwall=new ImageIcon("src/picture/堅果按鈕.png");
   ImageIcon bigpwall=new ImageIcon("src/picture/nobackwallbig.png");
   ImageIcon pflower=new ImageIcon("src/picture/nobackflower.png");
   ImageIcon fightbackground=new ImageIcon("src/picture/noback戰鬥背景.png");
   ImageIcon ground=new ImageIcon("src/picture/草地.png");
   ImageIcon powerblue=new ImageIcon("src/picture/能量.png");
   ImageIcon powerbox=new ImageIcon("src/picture/powerbox.jpg");
   ImageIcon powerframe=new ImageIcon("src/picture/能量條.png");
   ImageIcon peaground=new ImageIcon("src/picture/peaongroundswag.gif");
   ImageIcon wallground=new ImageIcon("src/picture/wallonground.png");
   ImageIcon peabullet=new ImageIcon("src/picture/豌豆子彈.png");
   ImageIcon woodenbox=new ImageIcon("src/picture/木箱背景.jpg");
   ImageIcon normalzombie=new ImageIcon("src/picture/normalzombie.gif");
   ImageIcon trizombie=new ImageIcon("src/picture/三角錐殭屍.gif");
   ImageIcon trizombie2=new ImageIcon("src/picture/三角錐殭屍.png");
   ImageIcon gameover=new ImageIcon("src/picture/1gameover.jpg");
   ImageIcon retry=new ImageIcon("src/picture/retry.png");
   ImageIcon levelchoosebackground=new ImageIcon("src/picture/木箱背景.jpg");
   ImageIcon levelwalleasy=new ImageIcon("src/picture/木頭標籤easy.png");
   ImageIcon levelwalleasy2=new ImageIcon("src/picture/木頭標籤easy滑過.png");
   ImageIcon levelwalleasy3=new ImageIcon("src/picture/木頭標籤easy按下.png");
   ImageIcon levelboss=new ImageIcon("src/picture/木頭標籤boss.png");
   ImageIcon levelboss2=new ImageIcon("src/picture/木頭標籤boss滑過.png");
   ImageIcon levelboss3=new ImageIcon("src/picture/木頭標籤boss按下.png");
   ImageIcon levelwallnormal=new ImageIcon("src/picture/木頭標籤normal.png");
   ImageIcon levelwallnormal2=new ImageIcon("src/picture/木頭標籤normal滑過.png");
   ImageIcon levelwallnormal3=new ImageIcon("src/picture/木頭標籤normal按下.png");
   ImageIcon levelwallhard=new ImageIcon("src/picture/木頭標籤hard.png");
   ImageIcon levelwallhard2=new ImageIcon("src/picture/木頭標籤hard滑過.png");
   ImageIcon levelwallhard3=new ImageIcon("src/picture/木頭標籤hard按下.png");
   ImageIcon start=new ImageIcon("src/picture/start.png");
   ImageIcon start2=new ImageIcon("src/picture/start2.png");
   ImageIcon exit=new ImageIcon("src/picture/exit.png");
   ImageIcon exitw=new ImageIcon("src/picture/exitw.png");
   ImageIcon help=new ImageIcon("src/picture/help.png");
   ImageIcon helpw=new ImageIcon("src/picture/helpw3.png");
   ImageIcon peaintroduce=new ImageIcon("src/picture/豌豆介紹.png");
   ImageIcon inbackground=new ImageIcon("src/picture/植物介紹背景.jpg");
   ImageIcon smallpea=new ImageIcon("src/picture/smallpea.png");
   ImageIcon wallintroduce=new ImageIcon("src/picture/堅果介紹.png");
   ImageIcon smallwall=new ImageIcon("src/picture/nobackwall.png");
   ImageIcon zombie1introduce=new ImageIcon("src/picture/普通僵屍介紹.png");
   ImageIcon trizombie1introduce=new ImageIcon("src/picture/三角錐僵屍介紹.png");
   ImageIcon smallzombie1=new ImageIcon("src/picture/normalzombie.png");
   ImageIcon helpback=new ImageIcon("src/picture/殭屍離開.png");
   ImageIcon zombieeat=new ImageIcon("src/picture/zombieeat.gif");
   ImageIcon trizombieeat=new ImageIcon("src/picture/三角錐殭屍吃.gif");
   ImageIcon close=new ImageIcon("src/picture/close.png");
   ImageIcon zombieddie=new ImageIcon("src/picture/殭屍倒下動畫2.png");
   ImageIcon zombieddie2=new ImageIcon("src/picture/殭屍倒下動畫4.png");
   ImageIcon zombieddie3=new ImageIcon("src/picture/殭屍倒下動畫5.png");
   ImageIcon zombieddie4=new ImageIcon("src/picture/殭屍倒下動畫3.png");
   ImageIcon victory=new ImageIcon("src/picture/victory.png");
   ImageIcon con=new ImageIcon("src/picture/continue_button.png");
   ImageIcon conup=new ImageIcon("src/picture/continue_buttonup.png");
   ImageIcon conpress=new ImageIcon("src/picture/continue_buttonpress.png");
   ImageIcon helpb=new ImageIcon("src/picture/help背景.jpg");
   ImageIcon gameintro=new ImageIcon("src/picture/遊戲介紹.png");
   ImageIcon chaintro=new ImageIcon("src/picture/角色介紹.png");
   ImageIcon levelintro=new ImageIcon("src/picture/關卡資訊.png");
   ImageIcon attack=new ImageIcon("src/picture/attack.jpg");
   ImageIcon bossimage=new ImageIcon("src/picture/boss.png");
   ImageIcon shine1=new ImageIcon("src/picture/雷電1.png");
   ImageIcon shine2=new ImageIcon("src/picture/雷電2.png");
   ImageIcon shine3=new ImageIcon("src/picture/雷電3.png");
   ImageIcon shine4=new ImageIcon("src/picture/雷電4.png");
   ImageIcon shine5=new ImageIcon("src/picture/雷電5.png");
   ImageIcon shine6=new ImageIcon("src/picture/雷電6.png");
   ImageIcon shine7=new ImageIcon("src/picture/雷電7.png");
   ImageIcon shine8=new ImageIcon("src/picture/雷電8.png");
   ImageIcon shine9=new ImageIcon("src/picture/雷電9.png");
   ImageIcon shine10=new ImageIcon("src/picture/雷電10.png"); 
   ImageIcon shine11=new ImageIcon("src/picture/雷電11.png");
   ImageIcon shine12=new ImageIcon("src/picture/雷電12.png");
}


